name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up GNAT toolchain
      run: |
        sudo apt-get update
        sudo apt-get install gnat gprbuild
        sudo apt install sphinx
        pip install sphinx_rtd_theme
        pip install --upgrade Pygments

    - name: Download and extract aunit
      run: >
        wget https://github.com/AdaCore/aunit/archive/refs/tags/v24.0.0.zip &&
        unzip v24.0.0.zip -d aunit &&
        cd aunit &&
        make
    
    - name: Build
      run: gprbuild -j0 -p

    - name: Run Test
      run: |
        cd test
        make
        ./obj/test_modbus
